package test_task.exceptions;

public final class SequenceFoundException extends RuntimeException{
    public SequenceFoundException(String message){super(message);}
}
